### ISSUE TITLE
Module import error

### ISSUE THREAD

**Issue by HadaHector** [SocketByte/SDToolkit#1]
I just installed the software, and when I tried using it (text to image), there is a python error, that prevents generating images.

```
(base) D:\Programs\SDToolkit>acttivate ldm
(ldm) D:\Programs\SDToolkit>cd stable-diffusion
(ldm) D:\Programs\SDToolkit\stable-diffusion>python optimizedSD/optimized_txt2img.py --prompt "a teddy bear with a yellow hat" --sampler plms --H 512 --W 512 --seed 0 --precision autocast --n_iter 1 --n_samples 8 --ddim_steps 50
Traceback (most recent call last):
  File "optimizedSD/optimized_txt2img.py", line 15, in <module>
    from ldm.util import instantiate_from_config
ModuleNotFoundError: No module named 'ldm'
(ldm) D:\Programs\SDToolkit\stable-diffusion
```
If you need more info, just ask, but I think any hardware info is not necessary for this problem.
I already had python installed, idk if that matters (PATH settings or anything)

**Comment by SocketByte** [comment]
Hey, that was due to incorrect sys.path references to libraries. Now it should install necessary components automatically if it doesn't find them, so the only thing you need patched is the .exe file.
https://github.com/SocketByte/SDToolkit/releases/tag/v0.2-beta1
Please try and let me know if that fixed the issue.

**Comment by HadaHector** [comment]
Thanks for the fast fix, the ldm issue is solved.
However I just got an another problem. When generating an image, and the sampler finishes, the whole app crashes. Maybe it has a problem with the upscaling (video2x).

I tried screenshotting the last moment:
![image](https://user-images.githubusercontent.com/3234713/196038587-05784774-36fb-431e-b216-c2c67c8d30e4.png)

Also I found the 8 generated images in the outputs folder, so the SD part is working.

The log file the output is referencing contains this:
![image](https://user-images.githubusercontent.com/3234713/196038730-1a48bd27-00ab-4f32-af75-02f6fe6437b7.png)

**Comment by SocketByte** [comment]
Oh no, yes, that makes sense. The issue is that video2x has a bug on Windows that requires the path to the RealSR model to be absolute. I forgot to apply that during the installation 🤦🏻 

For now you can go to video2x/video2x.yaml, and modify:
```yaml
realsr_ncnn_vulkan:
  path: 'C:\Users\Vaeliar\source\repos\SDToolkit\SDToolkit\bin\Debug\video2x\dependencies\realsr-ncnn-vulkan\realsr-ncnn-vulkan'
```
to your absolute path.

**Comment by HadaHector** [comment]
Alright, now it works! Thank for fixing these issues. 
Perhaps I will come back with some feedback :)
